env:
  browser: true
  node: true

parserOptions:
  sourceType: module
  ecmaVersion: 2015

extends:
  - eslint: recommended
  - prettier

plugins: 
  - prettier

rules:
  quotes:
    - error
    - single
  indent:
    - error
    - 4
